import type { Metadata } from 'next'
import './globals.css'

export const getServerSideProps = () => {};
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="tbody">{children}</body>
    </html>
  )
}
